version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      - REPOSITORY_URI_1=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME_1
      - REPOSITORY_URI_2=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME_2
      - REPOSITORY_URI_3=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME_3
      
      - IMAGE_TAG_BACK=$CODEBUILD_BUILD_NUMBER
      - IMAGE_TAG_PROM=$CODEBUILD_BUILD_NUMBER
      - IMAGE_TAG_GRAF=$CODEBUILD_BUILD_NUMBER


  build:
    commands:
      - echo "Renaming appspec-ecs.yml to appspec.yml"
      - cp appspec-ecs.yml appspec.yml
      - cd frontend/
      - npm install 
      - npm run build

      - cd ../backend/
      - docker build -t $REPOSITORY_URI_1:latest .
      - echo Build completed on `date`
      - docker pull prom/prometheus:latest
      - docker pull grafana/grafana-oss:latest

      - docker tag $REPOSITORY_URI_1:latest $REPOSITORY_URI_1:$IMAGE_TAG_BACK
      - docker tag prom/prometheus:latest $REPOSITORY_URI_2:latest
      - docker tag prom/prometheus:latest $REPOSITORY_URI_2:$IMAGE_TAG_PROM
      - docker tag grafana/grafana-oss:latest $REPOSITORY_URI_3:latest
      - docker tag grafana/grafana-oss:latest $REPOSITORY_URI_3:$IMAGE_TAG_GRAF

      - docker images
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI_1:latest
      - docker push $REPOSITORY_URI_1:$IMAGE_TAG_BACK

      - docker push $REPOSITORY_URI_2:latest
      - docker push $REPOSITORY_URI_2:$IMAGE_TAG_PROM
      
      - docker push $REPOSITORY_URI_3:latest
      - docker push $REPOSITORY_URI_3:$IMAGE_TAG_GRAF

      - cd ../admin/
      - npm install 
      - npm run build

      
artifacts:
  files:
    - appspec.yml
    # - docker-compose.yml
    # - start.sh
    - prometheus-config.yml
  name: backend_artifacts
  discard-paths: yes

  secondary-artifacts:
    admin_artifacts:
      base-directory: admin/dist
      files:
        - '**/*'
      name: admin_artifacts
      discard-paths: no

    frontend_artifacts:
      base-directory: frontend/dist
      files:
        - '**/*'
      name: frontend_artifacts
      discard-paths: no