version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=Backend_Build-$CODEBUILD_BUILD_NUMBER


  build:
    commands:
      - echo "Renaming appspec-ec2.yml to appspec.yml"
      - cp appspec-ec2.yml appspec.yml
      - cd frontend/
      - npm install 
      - npm run build

      - cd ../backend/
      - docker build -t $REPOSITORY_URI:latest .
      # - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - echo Build completed on `date`
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      # - docker tag imriteek:$CODEBUILD_BUILD_NUMBER imriteek:backend
      - docker images
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      # - docker push imriteek:$CODEBUILD_BUILD_NUMBER
      # - docker push imriteek:backend

      - cd ../admin/
      - npm install 
      - npm run build

      
artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - start.sh
    - prometheus-config.yml
  name: backend_artifacts
  discard-paths: yes

  secondary-artifacts:
    admin_artifacts:
      base-directory: admin/dist
      files:
        - '**/*'
      name: admin_artifacts
      discard-paths: no

    frontend_artifacts:
      base-directory: frontend/dist
      files:
        - '**/*'
      name: frontend_artifacts
      discard-paths: no