AWSTemplateFormatVersion: '2010-09-09'
Description: AWS ECS Cluster


Parameters:
  ClusterName: mycluster
    Type: String
    Description: Name of the ECS cluster where the service will be deployed

Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: my-ecs-service
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition  
      LaunchType: EC2  
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED 
          Subnets:
            - subnet-12345678  
          SecurityGroups:
            - sg-12345678  

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my_first_task
      NetworkMode: bridge
      ContainerDefinitions:
        - Name: nginx
          Image: nginx:latest
          Cpu: 256
          Memory: 512
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

